name: hyp3-srg
channels:
  - conda-forge
  - nodefaults
dependencies:
  # TODO: hyp3lib fails to import `cgi` which has been removed in Python 3.13: https://docs.python.org/3/library/cgi.html
  #   we should decide how to resolve this
  - python>=3.10
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - asf_search
  # For running
  - hyp3lib>=3,<4
  - s1_orbits
