name: hyp3-srg
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For packaging, and testing
  - ruff
  - mypy
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - asf_search
  # For running
  - hyp3lib>=3,<4
  - s1_orbits
