name: Test and build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
      - search-s3

jobs:
  call-pytest-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-pytest.yml@v0.11.2
    with:
      local_package_name: hyp3_srg
      python_versions: >-
        ["3.10", "3.11", "3.12"]

  call-version-info-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-version-info.yml@v0.11.2
    with:
      python_version: "3.10"

  call-docker-ghcr-workflow-cpu:
    needs: call-version-info-workflow
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-docker-ghcr.yml@specify-docker-file
    with:
      version_tag: ${{ needs.call-version-info-workflow.outputs.version_tag }}.cpu
      release_branch: main
      develop_branch: develop
      user: tools-bot
      file: Dockerfile.cpu
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call-docker-ghcr-workflow-gpu:
    needs: call-version-info-workflow
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-docker-ghcr.yml@specify-docker-file
    with:
      version_tag: ${{ needs.call-version-info-workflow.outputs.version_tag }}.gpu
      release_branch: main
      develop_branch: develop
      user: tools-bot
      file: Dockerfile
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
